[pytest]
filterwarnings =
    ignore::DeprecationWarning:casatools\.
    ignore::DeprecationWarning:dsacalib\.
    ignore::DeprecationWarning:fontTools\.
    ignore::astropy.utils.exceptions.AstropyWarning
    ignore::erfa.core.ErfaWarning
    ignore:numpy.ndarray size changed:RuntimeWarning

